[template]
src = "create-20postgresql.conf.sh.tmpl"
dest = "/create-20postgresql.conf.sh"
keys = [
  "/containers",
  "/stacks",
]

reload_cmd = "sh /create-20postgresql.conf.sh && /usr/bin/sv force-reload collectd"
